# Sciezka do folderu z plikami testowymi (musi konczyc sie slashem!)
data_folder=./data/
output_file=results.csv
show_progress=1

# Ile powtorzen wywolania calego algorytmu dla dokladniejszego sredniego czasu
repeats=10

# Ile sciezke wygenerowac i sprawdzic w ramach 1 wywolania algorytmu losowego
rand_local_repeats=100000

# Rodzaj badania (1 - Algorytmy RAND, NN, RNN, 2 - BF, 3 - Wszystkie)
test_type=1