# Konfiguracja do zbicia grafów z dużym błędem poniżej 15%

# Sciezka do folderu z plikami testowymi (musi konczyc sie slashem!)
data_folder=./big_data/
output_file=results-tsplib-big.csv
show_progress=1

# Liczba powtorzen dla dokladniejszego sredniego czasu
repeats=1

# Wspolczynnik chlodzenia (np. 0.95, 0.98, 0.99, 0.999)
cooling_rate=0.999

# Temperatura poczatkowa (-1 oznacza ze zostanie ona wyznaczona automatycznie)
initial_temp=-1

# Temperatura koncowa (warunek stopu)
final_temp=0.1

# Liczba iteracji na poziom temperatury (długość epoki)
iter_per_temp=1000

# Rodzaj sasiedztwa: 1=SWAP, 2=INVERT, 3=INSERT
neighbourhood=2

# Metoda inicjalizacji: 0=RANDOM, 1=NN, 2=RNN
init_method=1

# Schemat chlodzenia: 0=geometryczny, 1=liniowy, 2=logarytmiczny
cooling_schedule=2

# Limit czasu podany w minutach dla danej instancji
time_limit_min=15