# Sciezka do folderu z plikami testowymi (musi konczyc sie slashem!)
data_folder=./data_generated/
output_file=results.csv
show_progress=1

# Liczba powtorzen dla dokladniejszego sredniego czasu
repeats=1

# Wspolczynnik chlodzenia (np. 0.95, 0.98, 0.99, 0.999)
cooling_rate=0.99,0.999

# Temperatura poczatkowa
initial_temp=100,1000,10000

# Temperatura koncowa (warunek stopu)
final_temp=0.1

# Liczba iteracji na poziom temperatury
iter_per_temp=100,500

# Rodzaj sasiedztwa: 1=SWAP, 2=INVERT, 3=INSERT
neighbourhood=1,2,3

# Metoda inicjalizacji: 0=RANDOM, 1=NN, 2=RNN
init_method=2

# Schemat chlodzenia: 0=geometryczny, 1=liniowy, 2=logarytmiczny
cooling_schedule=1,2

# Limit czasu podany w minutach dla danej instancji
time_limit_min=5