# Sciezka do folderu z plikami testowymi (musi konczyc sie slashem!)
data_folder=./data_generated/
output_file=results.csv
show_progress=1

# Ile powtorzen wywolania calego algorytmu dla dokladniejszego sredniego czasu
repeats=1

# Ile sciezke wygenerowac i sprawdzic w ramach 1 wywolania algorytmu losowego
rand_local_repeats=1000

# Metoda wyliczeniea gornego ograniczenia 1 - RAND, 2 - NN, 3 - RNN
upper_bound_method=3

# Limit czasu podany w minutach dla danej instancji
time_limit_min=5

# Limit pamięci na instancję w MB
memory_limit_mb=5000

# Rodzaj badania
test_type=1
